version: '3'
services:
  db:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    ports:
      - '3307:3306'
    restart: always
    cap_add:
      - "SYS_NICE"
  backend:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - '3000:3000'
    links:
      - db
